---
title: "Emergence"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

theme_cw <- function () { 
  theme_bw(base_size=12) %+replace% 
    theme(
      panel.background = element_blank(), 
      plot.background = element_blank(), 
      axis.ticks = element_line(colour = "grey70", size = rel(0.5)),
      panel.grid.minor = element_blank(), 
      panel.grid.major.x = element_blank(),
      legend.background = element_blank(), 
      legend.key = element_blank(),
      strip.background = element_blank(), 
     # axis.text=element_text(size=12),
     # strip.text=element_text(size=12),
      complete = TRUE
      )
}

datpath <- "~/Dropbox/Lagged-Precip/Data/"

trt.key <- read.csv(paste0(datpath, "Plot-Layouts/block-key.csv")) %>%
  select(block:treatment)

sp.key <- read.csv(paste0(datpath, "stipa-avena_species-list.csv")) %>%
  select(c(species.code, group))


cover <- read.csv(paste0(datpath, 
                    'Fecundity_2022-04/fecundity_2022-04_entered-data/lagged-precip_spring-fecundity_2022-04-13.csv'))

plot.key <- cover %>% select(block:treatment)

```

## Emergence data from Jan 2022

```{r emergence-data}


emer <- read.csv(paste0(datpath, 
                    'Emergence_2022-01/emergence-entered-data/lagged-precip_emergence_2022-01-25.csv')) %>%
  mutate(weed.total = weed.forb + weed.grass + weed.moss) %>%
  left_join(trt.key, by = 'block') 

```


```{r emergence-prelim}

emer.sum <- emer %>% 
  pivot_longer(cols = c(av, ss, sp.phyto, weed.forb, weed.grass, weed.moss, weed.total),
               names_to = "species",
               values_to = "quantity") %>%
  group_by(treatment, bg, species) %>%
  dplyr::summarise(
    quantity.mean = mean(quantity),
    quantity.present = sum(quantity > 0),
    quantity.sd = sd(quantity)
  )


ggplot(filter(emer.sum, species %in% c('ss','av')), 
       aes(x = treatment, y = quantity.mean, ymin = quantity.mean - quantity.sd,
           ymax = quantity.mean + quantity.sd, color = species)) +
  facet_wrap(vars(bg), scales = "free") +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5))+
  theme_cw()

# how many plots have phytometers present? Note that there are 16 control plots per climate treatment
# but only 8 of the other backgrounds
ggplot(filter(emer.sum, species %in% c('ss','av', 'sp.phyto')), 
       aes(x = treatment, y = quantity.present, color = species,
           fill = species)) +
  facet_wrap(vars(bg), scales = "free_x") +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_cw()


```


## Weed cover data from April 2022
Note that the data used here hasn't been fully updated with the May Stipa tiller counts
```{r emergence-data}

cover <- read.csv(paste0(datpath, 
                    'Fecundity_2022-04/fecundity_2022-04_entered-data/lagged-precip_spring-fecundity_2022-04-13.csv'))

plot.key <- cover %>% select(block:treatment)

cover.long <- cover %>% 
  pivot_longer(cols = aircar:unkgrass_tiny_avena, 
               names_to = 'species', values_to = 'cover',
               values_drop_na = TRUE) %>%
  left_join(sp.key, by = c("species" = "species.code"))

cover.long.summary <- cover.long %>%
  filter(species != 'avefat') %>%
  group_by(block,plot, group) %>%
  dplyr::summarise(
    total.cover = sum(cover),
    num.species = length(cover)
  ) %>%
  ungroup() %>%
  complete(block, plot, group,
           fill = list(total.cover = 0, num.species = 0)) %>%
  left_join(plot.key, by = c('block', 'plot'))

```

Plotting weedy cover
```{r}

cover.long.sum.2 <- cover.long.summary %>% 
  group_by(bg, treatment, group) %>%
  dplyr::summarise(
    cover.mean = mean(total.cover),
    cover.se = sd(total.cover)/sqrt(length(total.cover)),
    rich.mean = mean(num.species),
    rich.se = sd(num.species)/sqrt(length(num.species))
  )

ggplot(cover.long.sum.2, 
       aes(x = bg, y = cover.mean, ymin = cover.mean - cover.se, ymax = cover.mean + cover.se,
           color = treatment)) +
  facet_wrap(vars(group), scales = 'free') +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  theme_cw()
ggsave('~/Dropbox/Lagged-Precip/Prelim-Figures/weedy-cover-group.pdf', width = 12, height = 6, units = 'in')

ggplot(cover.long.sum.2, 
       aes(x = bg, y = rich.mean, ymin = rich.mean - rich.se, ymax = rich.mean + rich.se,
           color = treatment)) +
  facet_wrap(vars(group), scales = 'free') +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  theme_cw()
ggsave('~/Dropbox/Lagged-Precip/Prelim-Figures/weedy-rich-group.pdf', width = 12, height = 6, units = 'in')

cover.long.sum.3 <- cover.long.summary %>% 
  group_by(bg, treatment) %>%
  dplyr::summarise(
    cover.mean = mean(total.cover),
    cover.se = sd(total.cover)/sqrt(length(total.cover)),
    rich.mean = mean(num.species),
    rich.se = sd(num.species)/sqrt(length(num.species))
  )

ggplot(cover.long.sum.3, 
       aes(x = bg, y = cover.mean, ymin = cover.mean - cover.se, ymax = cover.mean + cover.se,
           color = treatment)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  theme_cw()
ggsave('~/Dropbox/Lagged-Precip/Prelim-Figures/weedy-cover-total.pdf', width = 6, height = 4, units = 'in')

ggplot(cover.long.sum.3, 
       aes(x = bg, y = rich.mean, ymin = rich.mean - rich.se, ymax = rich.mean + rich.se,
           color = treatment)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5)) +
  theme_cw()
ggsave('~/Dropbox/Lagged-Precip/Prelim-Figures/weedy-rich-total.pdf', width = 6, height = 4, units = 'in')

```
# Fecundity
Fecundity data for Stipa and Avena in 2022
```{r fecundity-2022}
focal <- read.csv(paste0(datpath, 
                    'Fecundity_2022-04/fecundity_2022-04_entered-data/lagged-precip_spring-fecundity_focals_2022-04-13.csv'))

av.all <- c("av_1", "av_2", "av_3", "av_4", "av_5")
sp.all <- c("sp_p", "sp_big_c", "sp_big_l", "sp_big_r")

# stipa seeds per tiller
stipa.seeds <- read.csv(paste0(datpath,
                          'Fecundity_2022-04/fecundity_2022-04_entered-data/lagged-precip_stipa-seeds_2022-04-13.csv'))
stipa.seeds.per.tiller <- as.integer(mean(stipa.seeds$seeds))

# may also want to update avena seed counts based on immature tiller counts
# have to decide whether to do that on a plant-by-plant basis or across averages

focal <- focal %>% 
  left_join(plot.key, by = c("block", "plot")) %>%
  mutate(seed = ifelse(focal %in% av.all, awns * 2, tillers*stipa.seeds.per.tiller),
         diam = size) 


stipa <- focal %>% filter(focal %in% sp.all) %>%
  mutate(size = ifelse(focal == "sp_p", "phyto", "big"))

hist(stipa$seed)
hist(stipa$diam)

ggplot(stipa, aes(x = diam, y = seed, 
                  color = size, shape = treatment,
                  lty = treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_cw()

stipa.wide <- stipa %>% pivot_wider(names_from = "species", values_from = "count", values_fill = 0) %>%
  select(-c(awns, tillers_im, diseased))

stipa_dat <- stipa.wide %>% 
  select(-c(plot, focal, tillers, bg, diam))

```

