---
title: "stipa-forb_figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rstan)
library(HDInterval)
load("stipa-forb_final-fit_3.rdata")

#source("Emergence.Rmd")
species_names <- stipa_dat %>% 
  select(-c(block, size, treatment, seed)) %>%
  names()
S <- species_names %>% length() 
```


```{r pars}
post <- rstan::extract(FinalFit)
species.include <- tibble(species_names, inclusion_ij = Inclusion_ij, 
                          inclusion_eij = Inclusion_eij, num = 1:36)



# empty data frame
plot.vals <- tibble(drought = c(0, 1), size_big = c(0, 1), 
                    value = c("lambda", "alpha_gen")) %>% 
  expand(drought, size_big, value) %>%
  add_column(species = "focal") %>%
  add_row(drought = 0, size_big = 0, value = "alpha_eij", species = species_names) %>%
  add_row(drought = 0, size_big = 1, value = "alpha_eij", species = species_names) %>%
  add_row(drought = 1, size_big = 0, value = "alpha_eij", species = species_names) %>%
  add_row(drought = 1, size_big = 1, value = "alpha_eij", species = species_names) %>%
  add_column(mean = 0, lower = 0, upper = 0) 

plot.vals.2 <- plot.vals %>% left_join(species.include, by = c("species" = "species_names"))



plot.vals.3 <- plot.vals.2 %>%
  group_by(drought, size_big, num) %>%
  mutate(
    mean = case_when(
      value == "lambda" ~ mean(exp(post$lambda_0 + post$lambda_drought * drought + post$lambda_size * size_big)),
      value == "alpha_gen" ~ mean(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big + post$alpha_generic_drought * drought)),
    #  TRUE ~ mean(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big +
     #                  inclusion_ij * post$alpha_hat_ij[,num] +
      #                  (post$alpha_generic_drought + inclusion_eij * post$alpha_hat_eij[,num]) * drought))
    TRUE ~ mean(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big +
                       inclusion_ij * post$alpha_hat_ij[,num] +
                        (post$alpha_generic_drought + inclusion_eij * post$alpha_hat_eij[,num]) * drought))
   # TRUE ~ 0
    ),
    lower = case_when(
      value == "lambda" ~ HDInterval::hdi(exp(post$lambda_0 + post$lambda_drought * drought + post$lambda_size * size_big))[["lower"]],
      value == "alpha_gen" ~ HDInterval::hdi(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big + post$alpha_generic_drought * drought))[["lower"]],
      TRUE ~ 0
     # TRUE ~ HDInterval::hdi(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big +
    #                    inclusion_ij * post$alpha_hat_ij[,num] +
    #                    (post$alpha_generic_drought + inclusion_eij * post$alpha_hat_eij[,num]) * drought))[[1]] 
    ),
    upper = case_when(
      value == "lambda" ~ HDInterval::hdi(exp(post$lambda_0 + post$lambda_drought * drought + post$lambda_size * size_big))[["upper"]],
      value == "alpha_gen" ~ HDInterval::hdi(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big + post$alpha_generic_drought * drought))[["upper"]],
      TRUE ~ 0
    #  TRUE ~ HDInterval::hdi(exp(post$alpha_generic_0 + post$alpha_generic_size * size_big +
    #                    inclusion_ij * post$alpha_hat_ij[,num] +
    #                    (post$alpha_generic_drought + inclusion_eij * post$alpha_hat_eij[,num]) * drought))[[2]]
    )
  )

plot.vals.3$size <- ifelse(plot.vals.3$size_big == 0, "phytometer", "gallon")
plot.vals.3$treatment <- ifelse(plot.vals.3$drought == 0, "ambient", "drought")

```

```{r lambda-plot}
plot.vals.gen <- filter(plot.vals.3, species == "focal")

plot.vals.gen %>% 
  ggplot(aes(x = treatment, y = mean, ymin = lower, ymax = upper)) +
  facet_grid(rows = vars(value), cols = vars(size),
             scales = "free") +
  geom_point() +
  geom_errorbar() +
  theme_cw()
ggsave('stipa-forb_prelim-fig_lambda.pdf', width = 6, height = 4, units = 'in')


plot.vals.aeij <- filter(plot.vals.3, value == "alpha_eij", size_big == 0)

plot.vals.aeij %>% 
  ggplot(aes(x = species, y = log(mean), ymin = log(lower), ymax = log(upper),
             color = factor(inclusion_ij), shape = factor(inclusion_eij))) +
  facet_wrap(vars(treatment)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(width = 0.2, position = position_dodge(width = 0.5)) +
  theme_cw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave('stipa-forb_prelim-fig_alphas.pdf', width = 11, height = 4, units = 'in')


```


```{r abundance}
sp.abundance <- stipa %>%
  group_by(species, treatment) %>%
  dplyr::summarise(
    count.sum = sum(count)
  ) %>%
  filter(!(species == 'none'))

plot.vals.4 <- plot.vals.3 %>% left_join(sp.abundance, by = c("species", "treatment"))
plot.vals.4 <- plot.vals.4 %>% 
  mutate(
    count.sum = ifelse(value == "alpha_eij" && is.na(count.sum), 0, count.sum) 
  )

plot.vals.aeij <- filter(plot.vals.4, value == "alpha_eij", size_big == 0)

plot.vals.aeij %>% 
  ggplot(aes(x = log(count.sum+1), y = log(mean), ymin = log(lower), ymax = log(upper),
             color = factor(inclusion_ij), shape = factor(inclusion_eij))) +
  facet_wrap(vars(treatment)) +
  geom_point() +
  geom_errorbar() +
  theme_cw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#ggsave('stipa-forb_prelim-fig_alphas-2.pdf', width = 11, height = 4, units = 'in')


```
